### ISSUE TITLE
Variables only show up in debug mode

### ISSUE THREAD

**Issue by pwahlmueller** [TylerLeonhardt/vscode-inline-values-powershell#2]
Would it be possible to show the inline values even when there is no debugging at the moment?
Maybe only, if the values are not empty/null?

**Comment by TylerLeonhardt** [comment]
Sadly this feature is only available when you are stopped at a breakpoint in VS Code. It's kinda out of my control for now. I'm going to close this but I think this is the big issue that needs to be solved:
https://github.com/PowerShell/vscode-powershell/issues/1204
