### ISSUE TITLE
Ignore known PowerShell constants

### ISSUE THREAD

**Issue by fflaten** [TylerLeonhardt/vscode-inline-values-powershell#4]
Maybe ignore hard-coded variables like null, true and false?

`$null = $null` is waste of space that can be better utilized.

**Comment by TylerLeonhardt** [comment]
@fflaten great idea! This is a really simple feature request. Wanna try contributing? I can walk you through it.

We already have the variable name here:
https://github.com/TylerLeonhardt/vscode-inline-values-powershell/blob/master/src/powerShellVariableInlineValuesProvider.ts#L19

So all you have to do is check to see if the variable name is `$null` or whatever and if it is, `continue` the loop.

I just added steps on how to contribute here:
https://github.com/TylerLeonhardt/vscode-inline-values-powershell#development

**Comment by TylerLeonhardt** [comment]
Released :) 0.0.5 should show up in a few minutes.
